server:
  port: 8080

spring:
  application:
    name: qiyuan
  datasource:
    url: jdbc:sqlserver://localhost:11433;databaseName=qiyuan;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 1qaz@WSX
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10  # 可選：調整最大連線池大小
  web:
    resources:
      add-mappings: false
    mvc:
      throw-exception-if-no-handler-found: true
  mail:
    host: localhost
    port: 1025
    username: test@test.com
    password: 123456
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

sso:
  front-url: localhost:4040/api/sso/
  expired-minute: 30

mybatis:
  mapper-locations: classpath:/mappers/*.xml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs


security:
  public-endpoints:
    - /swagger-ui.html
    - /swagger-ui/**
    - /v3/api-docs/**
    - /banner/**
    - /poem/**
    - /god/**
    - /lantern/**
    - /master/**
    - /user/login
    - /user/refresh
    - /user/register
    - /user/forget-password
    - /product/**
    - /test/mail/**
  response:
    exclude-paths:
      - /v3/api-docs
      - /swagger-ui
      - /swagger-ui.html

upload:
  image-path:
    banner: C:\Users\Public\test\banner
    master: C:\Users\Public\test\master
    offering: C:\Users\Public\test\offering
    produst: C:\Users\Public\test\product
  url-prefix:
    product: /images/product/
