server:
  port: 8080

spring:
  application:
    name: qiyuan
  datasource:
    url: jdbc:sqlserver://localhost:11433;databaseName=qiyuan;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 1qaz@WSX
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10  # 可選：調整最大連線池大小
  web:
    resources:
      add-mappings: false
    mvc:
      throw-exception-if-no-handler-found: true
  mail:
    host: localhost
    port: 1025
    username: test@test.com
    password: 123456
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: [ your-google-client-id ]
            client-secret: [ your-google-client-secret ]
            scope:
              - email
              - profile
          facebook:
            client-id: [ your-facebook-app-id ]
            client-secret: [ your-facebook-app-secret ]
            scope:
              - email


sso:
  front-url: localhost:4040/api/sso/
  expired-minute: 30

mybatis:
  mapper-locations: classpath:/mappers/*.xml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs


security:
  public-endpoints:
    - /swagger-ui.html
    - /swagger-ui/**
    - /v3/api-docs/**
    - /banner/**
    - /poem/**
    - /god/**
    - /lantern/**
    - /master/**
    - /user/login
    - /user/refresh
    - /user/register
    - /user/forget-password
    - /product/**
    - /test/mail/**
  response:
    exclude-paths:
      - /v3/api-docs
      - /swagger-ui
      - /swagger-ui.html
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5500
      - http://127.0.0.1:5500
      - https://myapp.com # 以這為案例將前端URL設置在此處


upload:
  image-path:
    banner: C:\Users\Public\test\banner
    master: C:\Users\Public\test\master
    offering: C:\Users\Public\test\offering
    product: C:\Users\Public\test\product
  url-prefix:
    product: /images/product/

gomypay:
  customerNo: 8F8ABEDD2FC67C38EEF644BF52831CE8
  pwd: jk5rjwzmk2f16h3t1n6qgx87tqhdy3ky
  api: https://n.gomypay.asia/TestShuntClass.aspx
  einvoice:
    api: http://testeinvoice.gomypay.asia/
    pwd: jk5rjwzmk2f16h3t1n6qgx87tqhdy3ky
    customerNo: 60755266

ap:
  backend: http://localhost:8080

