server:
  port: 8443
  ssl:
    enabled: true
    key-store: file:/etc/letsencrypt/live/api.ingodwetrust.tw/keystore.p12
    key-store-password: WUfan0667.
    key-store-type: PKCS12
    key-alias: tomcat


spring:
  application:
    name: qiyuan
  datasource:
    url: jdbc:sqlserver://chifu.cdi42o44miez.ap-northeast-1.rds.amazonaws.com:1433;databaseName=qiyuan;encrypt=true;trustServerCertificate=true;
    username: admin
    password: WUfan0667.
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10  # 可選：調整最大連線池大小
  web:
    resources:
      add-mappings: false
    mvc:
      throw-exception-if-no-handler-found: true
  mail:
    host: localhost
    port: 1025
    username: test@test.com
    password: 123456
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: sdfgfsdgsfdg 
            client-secret: sfghfghdfgh
            scope:
              - email
              - profile
          facebook:
            client-id: dgfhdgfhdghdfh
            client-secret: dghdgfhdgfh
            scope:
              - email


sso:
  front-url: localhost:4040/api/sso/
  expired-minute: 30

mybatis:
  mapper-locations: classpath:/mappers/*.xml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs


security:
  public-endpoints:
    - /swagger-ui.html
    - /swagger-ui/**
    - /v3/api-docs/**
    - /calendar/query
    - /oauth2/**
    - /banner/**
    - /poem/**
    - /god/**
    - /lantern/**
    - /master/**
    - /user/login
    - /user/refresh
    - /user/register
    - /user/forget-password
    - /user/reset-password/**
    - /product/**
    - /test/mail/**
    - /images/**
    - /master/reservation
  response:
    exclude-paths:
      - /v3/api-docs
      - /swagger-ui
      - /swagger-ui.html
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5500
      - http://127.0.0.1:5500
      - https://ingodwetrust.tw # 以這為案例將前端URL設置在此處
      - http://localhost:5173

#upload:
#  image-path:
#    banner: /home/ec2-user/godtrust/banner
#    master: /home/ec2-user/godtrust/master
#    offering: /home/ec2-user/godtrust/offering
#    product: /home/ec2-user/godtrust/product
#  url-prefix:
#    product: /images/product/
upload:
  image-path:
    banner: /home/ec2-user/godtrust/banner
    master: /home/ec2-user/godtrust/master
    offering: /home/ec2-user/godtrust/offering
    product: /home/ec2-user/godtrust/product
  url-prefix:
    product: /images/product/

gomypay:
  customerNo: 8F8ABEDD2FC67C38EEF644BF52831CE8
  pwd: jk5rjwzmk2f16h3t1n6qgx87tqhdy3ky
  api: https://n.gomypay.asia/TestShuntClass.aspx
  einvoice:
    api: http://testeinvoice.gomypay.asia/
    pwd: jk5rjwzmk2f16h3t1n6qgx87tqhdy3ky
    customerNo: 60755266
ap:
  backend: https://api.ingodwetrust.tw:8443


calendar-api:
  url: https://fortunetell.lifemap.com.tw/app/api/v1/chinese_calendar/
  token: uKdx9poTRM48nLo5HKPVuAMtqOTzcFSIEPLvk3oM5Fl0iIahlHhInage1kdaB4KT
  
app:
  oauth:
    redirectUrl: https://ingodwetrust.tw/oauth2/redirect

