server:
  port: 8080

spring:
  application:
    name: qiyuan
  datasource:
    url: jdbc:sqlserver://localhost:11433;databaseName=qiyuan;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 1qaz@WSX
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10  # 可選：調整最大連線池大小
  web:
    resources:
      add-mappings: false
    mvc:
      throw-exception-if-no-handler-found: true


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  public-endpoints:
    - /auth/login
    - /auth/refresh
    - /swagger-ui/**
    - /v3/api-docs/**
    - /banner/**
    - /poem/**
    - /god/**
    - /lantern/**

mybatis:
  mapper-locations: classpath:/mappers/*.xml
