server:
  port: 8080

spring:
  application:
    name: qiyuan
  datasource:
    url: jdbc:sqlserver://localhost:11433;databaseName=qiyuan;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 1qaz@WSX
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10  # 可選：調整最大連線池大小
  web:
    resources:
      add-mappings: false
    mvc:
      throw-exception-if-no-handler-found: true
  mail:
    host: smtp.gmail.com     # SMTP 伺服器（範例使用 Gmail）
    port: 587                # SMTP Port
    username: test      # 發信帳號
    password: your_app_password         # 密碼/應用程式密碼
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

mybatis:
  mapper-locations: classpath:/mappers/*.xml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  public-endpoints:
    - /swagger-ui.html
    - /swagger-ui/**
    - /v3/api-docs/**
    - /banner/**
    - /poem/**
    - /god/**
    - /lantern/**
    - /master/**
    - /user/login
    - /user/refresh
    - /user/register
    - /user/**
  response:
    exclude-paths:
      - /v3/api-docs
      - /swagger-ui
      - /swagger-ui.html

upload:
  image-path:
    banner: C:\Users\Public\test\banner
    master: C:\Users\Public\test\master
    offering: C:\Users\Public\test\offering
    produst: C:\Users\Public\test\product
